version: "3.1"

services:
  couchdb:
    image: couchdb:latest
    restart: always
    ports:
      - 5984:5984
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: plop
    networks:
      - api
  schools:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=plop
      - DATABASE_HOST=couchdb
      - LOG_LEVEL=debug
      - SALT=kikoo plop
    depends_on:
      - couchdb
      - couchdbsetup
    networks:
      - api

networks:
  api:
    driver: bridge