version: "3.1"

services:
  couchdb:
    image: couchdb:latest
    restart: always
    ports:
      - 5984:5984
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: plop
    networks:
      - api
  initializer:
    image: curlimages/curl
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - couchdb
    networks:
      - api
    command: ["sh","-c","sleep 15 && curl -u admin:plop -X PUT couchdb:5984/_users &&  curl -u admin:plop -X PUT couchdb:5984/test"]
  schools:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=plop
      - DATABASE_HOST=couchdb
      - LOG_LEVEL=debug
      - SALT=kikoo plop
    depends_on:
      - couchdb
      - initializer
    networks:
      - api

networks:
  api:
    driver: bridge